language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rusic-theme' ]; then cd .. && eval "mv $currentfolder generator-rusic-theme" && cd generator-rusic-theme; fi

